version: '3.3'

services:
  python:
    build: .
    image: thomaswillson/covid-dashboard-python
    restart: always
    volumes:
        - static_volume:/app/static
    environment: 
        - MEMCACHED_SERVER=memcached
    depends_on:
        - memcached

  nginx:
    build: ./containers/nginx
    image: thomaswillson/covid-dashboard-nginx
    restart: always
    ports:
        - 1337:80
    depends_on:
        - python
    volumes:
        - static_volume:/home/static

  memcached:
    image: memcached:1.6.6-alpine
    restart: always
    command: memcached -m 256 -I 64m

volumes:
  static_volume: