version: '3.3'

services:
  python:
    build: .
    image: thomaswillson/covid-dashboard-python
    restart: always
    volumes:
        - static_volume:/app/static

  nginx:
    build: ./containers/nginx
    image: thomaswillson/covid-dashboard-nginx
    restart: always
    ports:
        - 1337:80
    depends_on:
        - python
    volumes:
        - static_volume:/home/static
volumes:
  static_volume: